project_name: trzsz
before:
  hooks:
    - go mod tidy
builds:
  - id: trz
    main: ./cmd/trz
    binary: trz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: tsz
    main: ./cmd/tsz
    binary: tsz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: trzsz
    main: ./cmd/trzsz
    binary: trzsz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - id: trzsz
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
      arm64: aarch64
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
nfpms:
  - id: trzsz
    builds:
      - trz
      - tsz
      - trzsz
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
    homepage: https://trzsz.github.io/
    maintainer: Lonny Wong <lonnywong@qq.com>
    description: |-
      trzsz ( trz / tsz ) is a simple file transfer tools.
      similar to lrzsz ( rz / sz ), and compatible with tmux.
    license: MIT
    formats:
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        replacements:
          amd64: x86_64
    rpm:
      group: Unspecified
snapshot:
  name_template: '{{ .Version }}.next'
