name: Go test trzsz-go
on: [push]
jobs:
  go-test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.3"
      - name: go test
        run: go test -v -count=1 ./trzsz
  go-test-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.3"
      - name: go test
        run: go test -v -count=1 ./trzsz
  go-test-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout trzsz-go
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.3"
      - name: go test
        run: go test -v -count=1 ./trzsz
